services:
  pg:
    build:
      context: .
      dockerfile: ./docker/postgres-dockerfile
      args:
        ICHIRAN_DB_URL: "https://github.com/tshatrov/ichiran/releases/download/ichiran-250113/ichiran-250113.pgdump"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  main:
    build:
      context: .
      dockerfile: ./docker/sbcl-dockerfile
    container_name: ichiran-main
    volumes:
      - ichiran-bin:/ichiran-bin
    environment:
      PGHOST: pg
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: ichiran
    depends_on:
      - pg
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    container_name: ichiran-api
    volumes:
      - ichiran-bin:/ichiran-bin
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - "8000"
    depends_on:
      - main
      - pg
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: ichiran-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - api
    restart: unless-stopped

volumes:
  ichiran-bin:
  caddy-data:
  caddy-config:
