version: "3.9"

services:
  pg:
    build:
      dockerfile: ./docker/postgres-dockerfile
      context: .
      args:
        ICHIRAN_DB_URL: "https://github.com/tshatrov/ichiran/releases/download/ichiran-250113/ichiran-250113.pgdump"
    shm_size: "1gb"
    environment:
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data

  main:
    build:
      dockerfile: ./docker/sbcl-dockerfile
      context: .
    container_name: ichiran-main

  api:
    build:
      context: .
      dockerfile: ./docker/sbcl-dockerfile   # same as main
    command: >
      sh -c "apt-get update &&
             apt-get install -y python3 python3-pip &&
             pip3 install fastapi uvicorn &&
             uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./api:/app
    depends_on:
      - main
    ports:
      - "8000:8000"


  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - api
