services:
  pg:
    build:
      dockerfile: ./docker/postgres-dockerfile
      context: .
      args:
        ICHIRAN_DB_URL: "https://github.com/tshatrov/ichiran/releases/download/ichiran-250113/ichiran-250113.pgdump"
    environment:
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  main:
    build:
      dockerfile: ./docker/sbcl-dockerfile
      context: .
    container_name: ichiran-main
    volumes:
      - ichiran-bin:/ichiran-bin
    command: >
      sh -c "/ichiran-cli && cp ichiran-cli /ichiran-bin/ && tail -f /dev/null"
    restart: unless-stopped

  api:
    build:
      dockerfile: ./Dockerfile.api
      context: .
    container_name: ichiran-api
    volumes:
      - ichiran-bin:/ichiran-bin
    ports:
      - "8000:8000"  # only needed internally if you want to test on VPS
    depends_on:
      - main
      - pg
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    restart: unless-stopped

volumes:
  ichiran-bin:
  pgdata:
  caddy_data:
  caddy_config:
